version: '2'
services:
  cbrain:
    image: ${IMAGE_NAME}
    volumes:
     - ../../cbrain:/home/cbrain/cbrain_travis
    depends_on:
     - mysql
    environment:
      CBRAIN_FAILTEST: ${CBRAIN_FAILTEST}
      MYSQL_PORT: "3306"
      MYSQL_HOST: "mysql"
      MYSQL_USER: "cb_user"
      MYSQL_DATABASE: "cb_db_test"
      MYSQL_PASSWORD: "cbpw12345"
  mysql:
    image: mariadb:10.0
    volumes:
      - ../../../volumes/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_USER: "cb_user"
      MYSQL_DATABASE: "cb_db_test"
      MYSQL_PASSWORD: "cbpw12345"
